openapi: 3.0.1
info:
  title: TEST-EXTRACT-API
  description: ''
  version: '1.0'
servers:
  - url: https://apim-demo-hs0125.azure-api.net/url
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]